CREATE DATABASE todo_app;

-- Connect to todo_app before running the table setup below.

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT NOT NULL DEFAULT '',
  color VARCHAR(20) NOT NULL DEFAULT 'green',
  priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  category VARCHAR(30) NOT NULL DEFAULT 'other',
  due_date DATE DEFAULT CURRENT_DATE,
  due_time TIME,
  alarm_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  alarm_datetime TIMESTAMP,
  list_id INTEGER,
  position INTEGER NOT NULL DEFAULT 0,
  image_url TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_lists (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  color VARCHAR(20) DEFAULT 'green',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todo_comments (
  id SERIAL PRIMARY KEY,
  todo_id INTEGER NOT NULL REFERENCES todos(id) ON DELETE CASCADE,
  author VARCHAR(100) NOT NULL DEFAULT 'Maya',
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Default board lists
INSERT INTO board_lists (title, position, color) VALUES
  ('To Do', 0, 'blue'),
  ('In Progress', 1, 'yellow'),
  ('Done', 2, 'green')
ON CONFLICT DO NOTHING;

-- Migration helpers (safe to re-run)
ALTER TABLE todos
  ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS color VARCHAR(20) NOT NULL DEFAULT 'green',
  ADD COLUMN IF NOT EXISTS priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS category VARCHAR(30) NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS due_date DATE DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS due_time TIME,
  ADD COLUMN IF NOT EXISTS alarm_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS alarm_datetime TIMESTAMP,
  ADD COLUMN IF NOT EXISTS list_id INTEGER,
  ADD COLUMN IF NOT EXISTS position INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS image_url TEXT;
